services:
  web:
    image: aleksospishev/habits_project:latest
    container_name: habits_project
    command:  ./wait-for-it.sh postgres_db:5432 -- python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    depends_on:
      - db
      - redis

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf/nginx.conf.conf:/etc/nginx.conf/nginx.conf.conf
      - static_volume:/app/staticfiles
    depends_on:
      - web

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_worker
    command: >
      sh -c "celery -A drf_app worker --loglevel=info"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_beat
    command: >
      sh -c "celery -A config beat --loglevel=info"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis

  db:
    image: postgres:16
    container_name: postgres_db
    env_file:
      - ./.env
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis

volumes:
  postgres_data:
  static_volume: